### ISSUE TITLE
Double click a warning to go to that line

### ISSUE THREAD

**Issue by karlgrz** [OmniSharp/omnisharp-sublime#102]
![untitled](https://cloud.githubusercontent.com/assets/548140/5510227/874d0074-8785-11e4-88f0-16ed726e2d2d.png)

It would be a fantastic efficiency if I double clicked on the highlighted line if it focused on that line in the editor window.

Nudge me in the right direction and I'd be happy to submit a PR.

**Comment by jchannon** [comment]
Similar to #130 

Please feel free to send PRs

**Comment by jchannon** [comment]
Duplicate
