### ISSUE TITLE
No syntax error highlighting

### ISSUE THREAD

**Issue by sonoshee-desu** [OmniSharp/omnisharp-sublime#107]
I have installed the Omnisharp package and followed the instructions regarding Kulture and Python, but Omnisharp doesn't seem to work.
I guess the problem resides  in setting Python properly. I installed the 2.7.9 version from the Python website and added its path from here : My Computer > Properties > Advanced > Environment Variables : 
![screenshot_1](https://cloud.githubusercontent.com/assets/10574869/5789521/fcb61fce-9e66-11e4-9a3f-b97ead30abac.png)
Do you have any thorough tutorial on how should Omnisharp be installed ?

Note : I'm on Windows and I use Unity3D ( wth the Unity packages installed)

**Comment by jchannon** [comment]
Have you tried a reboot after changing the path?

**Comment by sonoshee-desu** [comment]
Yes I did reboot both Sublime and Windows.
How can I know for sure that Omnisharp is working ? I try to intentionally type a syntax mistake and wait for some kind of feedback, but nothing happens.

**Comment by jchannon** [comment]
Try putting spaces on your lines of code then try a format document from
the menu to see if it does it. You can also see results in View - Show
Console

**Comment by sonoshee-desu** [comment]
They said in the console that there was an error while formatting the document :
![screenshot_1](https://cloud.githubusercontent.com/assets/10574869/5789889/3319ee1a-9e76-11e4-8ebd-5085189febfd.png)

**Comment by jchannon** [comment]
You need to open the folder with the solution file in it. If you have
multiple solutions in the same folder then you need to create a sublime
project file pointing to the right sln file. It's explained more in the
readme

**Comment by sonoshee-desu** [comment]
Ah I followed the README.md instructions ( which I first didn't know exists) and OmniSharp works.
Is there any way of making the syntax highlighting enabled while I'm typing, because by default the syntax is only checked when I save the file.
Nevertheless, I must say it's an extremely helpful package!

**Comment by jchannon** [comment]
Not whilst you type I'm afraid. You could change the source code if you
like so it does that locally for you. So instead of on post save its on
modified

**Comment by jchannon** [comment]
There is a config setting that you can turn on and off now for this

**Comment by sonoshee-desu** [comment]
Hi jchannon, you said there was a config setting for checking syntax errors. Where is it?

**Comment by jchannon** [comment]
I think we changed it again. Sorry

**Comment by sonoshee-desu** [comment]
Ah okay but is there any solution for me to get syntax error highlighting? I desperately need it :p

**Comment by jchannon** [comment]
No. You only get it when saving the document.
