### ISSUE TITLE
Go to definition not working until OmniSharp.exe is ran from the command line

### ISSUE THREAD

**Issue by jkells** [OmniSharp/omnisharp-sublime#115]
This is a strange one. A fresh install of Sublime Text 3 and this plugin.

Go to definition doesn't work. In the Sublime debug window I get this back from every request
======== response ========
{"FileName":null,"Line":0,"Column":0}
callback data

Running the OmniSharp.exe manually with the same solution and a different port makes it work. It continues to work even after I've killed the OmniSharp server that I started manually.

I'm running Windows 8.1

**Comment by jchannon** [comment]
Cannot reproduce on latest version 1.8.1
