### ISSUE TITLE
Project reference doesn't work with autocomplete

### ISSUE THREAD

**Issue by nickgravelyn** [OmniSharp/omnisharp-sublime#119]
I have a project that has a project reference. While I can build (both command line with xbuild and using the OmniSharp Sublime Plugin), when I save, I get issues regarding all of the types/namespaces from the referenced project and the autocomplete also doesn't work for those types. Autocomplete for types in my project and system assemblies is working.

I'm on Mac OS X 10.10 with the latest Mono MDK installed (from the Mono project, not Homebrew) in case that changes anything.

**Comment by jchannon** [comment]
Can you put a git repo with an example up?

**Comment by nickgravelyn** [comment]
Just tried to make a repo (the project I originally was working on has since been deleted) and this issue seems to be working resolved when I built from source. The version on Package Control was failing to start the server because it didn't quote the `--config` option (which at least in my case had spaces) so technically I couldn't verify that the Package Control version didn't have the bug.
