### ISSUE TITLE
New C# class does not honor RootNamespace property of .kproj

### ISSUE THREAD

**Issue by bgeihsgt** [OmniSharp/omnisharp-sublime#124]
Repro steps:

- Create a .kproj that contains a RootNamespace element different than its folder structure.  For example:

project lives in folder: `ProjectRoot/src/MyProject`
`<RootNamespace>Foo.Bar</RootNamespace>`

- Right-click a folder within the project (call it MyFolder), new C# class 

Expected: The class gets namespace `Foo.Bar.MyFolder`

Actual: The class gets namespace `ProjectRoot.src.MyProject.MyFolder`

**Comment by jchannon** [comment]
Is this on the roslyn branch of the plugin as I know @markeendle recently
improved this

**Comment by jchannon** [comment]
Mark fixed it set namespace based on location of projcet.json see #121
