### ISSUE TITLE
AssemblyPath not as expected when running unit tests under windows

### ISSUE THREAD

**Issue by floekke** [OmniSharp/omnisharp-sublime#125]
Hi

When running a single test (sublime 3, windows) AssemblyPath is not bound to the correct dll:

nunit-console.exe -nologo "C:\Program Files\Sublime Text 3\bin\Debug\OrphanProject.dll" -run=WebIce.Tests.Server.Commons.DependencyInjections.DependencyInjectionTests.ShouldNotBeMissConfigured

From config.json:

"Single": "nunit-console.exe -nologo {{AssemblyPath}} -run={{TypeName}}.{{MethodName}}"

TypeName and MethodName is bound correctly..
Any suggestions on how to fix this?

**Comment by jchannon** [comment]
You need to be in a cs file within the test project when executing the Run Unit Tests option
