### ISSUE TITLE
Merge roslyn to master

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-sublime#129]
I think we need to stop maintaining two branches. Theres some cool stuff in roslyn like external python not needed that should go in master. @nosami suggested we package both servers. I sugest we then detect somehow which server to fire up and then enable certain features in the plugin. I assume we'd need to cherry pick commits from roslyn branch into master so not sure who's up for this task  @markrendle , @nosami ..

**Comment by davidfowl** [comment]
I suggest we package ROSLYN only :smile:

**Comment by jchannon** [comment]
Hurry up and make it as good as the first edition then :stuck_out_tongue:

**Comment by nosami** [comment]
I think that you're up for it @jchannon :)

**Comment by mat-mcloughlin** [comment]
sheeze he's lazy :)

**Comment by jchannon** [comment]
![](https://bintrayblog.files.wordpress.com/2013/10/lazyness.jpg)
