### ISSUE TITLE
Output results to Build Window

### ISSUE THREAD

**Issue by Jetski5822** [OmniSharp/omnisharp-sublime#130]
At the moment we output the results to a separate sublime output window, this does not allow us to go to error.

If we out put to the build window, we can add that functionality in.

**Comment by jchannon** [comment]
Output what results to the build window?

**Comment by nosami** [comment]
I think he means /codecheck for Roslyn. There isn't a way to jump to errors in the code.

**Comment by jchannon** [comment]
Ah.

The build window is a built in window that appears when commands are shell
executed ie/build & unittests

So you'd have to shell out to omnisharp to get the code checks i think

Also not sure on the effect of show server output state when you run
requests and try and run unit tests i assume the window will show a mixture
of server output and xunit output

**Comment by nosami** [comment]
Shelling out need not be an issue. You could use curl - sucks but it would
work - that's how emacs is communicating with the server.

On Thu, Mar 26, 2015 at 12:15 PM, Jonathan Channon <notifications@github.com
> wrote:

> Ah.
>
> The build window is a built in window that appears when commands are shell
> executed ie/build & unittests
>
> So you'd have to shell out to omnisharp to get the code checks i think
>
> Also not sure on the effect of show server output state when you run
> requests and try and run unit tests i assume the window will show a mixture
> of server output and xunit output
>

**Comment by jchannon** [comment]
If someone wants to do a PR then fine by me ;)

**Comment by tim241** [comment]
Closing due to having outdated information.
