### ISSUE TITLE
Use Sublime Tooltips for Type Lookup

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-sublime#132]
In OmniSharp Server we have a `/typelookup` endpoint that takes a `includeDocumentation` property.  We need to call it with `true` when we hover over a type (for longer than 1sec I'd say) and then use Sublime Text's brand new popup feature to display info. 

See here - http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583

There is quite a nice looking popup lib for Sublime in which we could "borrow" styling and code for hover detection and then just populate it with the omnisharp server results

See here - https://github.com/jbrooksuk/Intellitip

**Comment by jchannon** [comment]
We have error tooltips thanks to @karlgluck , hopefully type lookups should be relatively straight forward now

**Comment by karlgluck** [comment]
Hey folks! They should be straightforward but at the moment work on our game prototype has taken precedence so I haven't been able to contribute since that PR. I'll be adding more features as much as I can. We plan on making this our main dev environment so I expect much more in the future :)

**Comment by nosami** [comment]
That's great news! Thanks :)

**Comment by jchannon** [comment]
Brilliant! Can't wait

**Comment by tim241** [comment]
Closing due to having outdated information.
