### ISSUE TITLE
OmniSharp.exe Has Stopped Working

### ISSUE THREAD

**Issue by c-trimm** [OmniSharp/omnisharp-sublime#133]
As soon as I open a file in my project in Sublime Text 3, OmniSharp crashes, with a "OmniSharp.exe has stopped working, Windows is checking for a solution to the problem" dialog. Windows 7.

Console output:
```
solution_path:C:\Users\Casey\Documents\Projects\Maze\Maze.sln
omni_port:57401
LAUNCH!!! C:\Users\Casey\AppData\Roaming\Sublime Text 3\Packages\OmniSharp\launchers\omni_sharp_launcher.py
start_omni_sharp_launcher:C:\Users\Casey\Documents\Projects\Maze\Maze.sln
project file found
already_bound_solution:C:\Users\Casey\Documents\Projects\Maze\Maze.sln
exit_omni_sharp_launcher:C:\Users\Casey\Documents\Projects\Maze\Maze.sln
```

OmniSharp doesn't work after this, and when attempting to autocomplete, it just fails with
```
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

Which is likely because it's no longer a running process. :P

Any thoughts?

**Comment by jchannon** [comment]
Afraid not :(

**Comment by nosami** [comment]
Try starting the server manually in a terminal... see here https://github.com/OmniSharp/omnisharp-server.

**Comment by jchannon** [comment]
Please upgrade to 1.8.1 of the plugin and let me know if this is resolved

**Comment by Schr3da** [comment]
It seems like the latest build has some issue... It didn't work on my Mac either so is checked out  the "omnisharp-sublime-revert-117" version. Now its working again 
regards schrod

**Comment by jchannon** [comment]
1.8.1 isnt out yet. Please give it another 30mins. Also read the notes on `chmod` when the release notes pop up

**Comment by Jetski5822** [comment]
Just cloned this morning from the master branch and get this.

**Comment by Jetski5822** [comment]
Okay it looks like it needs to exist in the folder Omnisharp, not Omnisharp-Sublime

**Comment by jchannon** [comment]
Yup

**Comment by c-trimm** [comment]
Fixed it! As it turns out, I needed to install Visual Studio (or some component that gets installed with VS). I had only been using Unity + SublimeText, so perhaps all of the prerequisites for OmniSharp weren't there.

**Comment by jchannon** [comment]
You only need a sublime project file if you have more than one sln in the
root. I believe if there are 2 unity solutions the server will pick the
correct one cc @nosami

**Comment by dunachu** [comment]
Hello,
I also have this issue on Windows. (Mono and Python are in the PATH, it worked well until yesterday).
When i first get to a cs file, I have a window with "OmniSharp.exe has stop working"...
There are spaces in my Sublime project Path. I removed the quotes in the "omnisharp.py" but it doesn't work...
There is no chmod +x in Windows, Have i got to do something other than waiting a new version ?
For the moment, i started the omnisharpserver in a "cmd" console, but i hope it will be fixed soon...

**Comment by jchannon** [comment]
Windows should be calling this
https://github.com/OmniSharp/omnisharp-sublime/blob/master/PrebuiltOmniSharpServer/omnisharp.cmd

**Comment by dunachu** [comment]
Yes, it calls omnisharp.cmd which calls Omnisharp.exe with some parameters.
Even if i try to start omnisharp.cmd in the Sublime Console, it doesn't work...
Here is the output i got when Omnisharp crashes
![sans titre](https://cloud.githubusercontent.com/assets/10654649/6916960/a5c6abfc-d7a0-11e4-853b-3d5993a33d7a.png)
Hope it helps...

**Comment by jchannon** [comment]
I'm a bit baffled then. Only thing I can suggest is close sublime make sure
there are no omnisharp.exe running in Task Man and try again. I tried it on
Windows and had the same issue and after the quote removal it seemed ok but
it did seem to need about 5 restarts of sublime to work which is odd.

**Comment by dunachu** [comment]
Ok, it works now...
I restarted my pc, open Unity, rebuild the sln files and open Sublime and it works after that...
I don't know what happened... but it's OK now ;)

**Comment by jchannon** [comment]
Great! it seems very temperamental which isnt good :(
