### ISSUE TITLE
OmniSharp Crash on windows because of incorrect paths

### ISSUE THREAD

**Issue by Rikkos** [OmniSharp/omnisharp-sublime#152]
Experimenting with OmniSharp for sublime 3 on Windows 10. After startup, if I open any C# file, the sublime plugin tries to start OmniSharp and this results in the following crash. 

![image](https://cloud.githubusercontent.com/assets/397160/7004544/390e1046-dc6d-11e4-95b0-cdf9a783c785.png)

Events viewer indicates that there is an 

```
Exception Info: System.IO.FileNotFoundException
Stack:
   at OmniSharp.Program.StartServer(System.String, System.String, Int32, OmniSharp.Verbosity, System.String, Int32)
   at OmniSharp.Program.Main(System.String[])
```

Looking at the console in sublime I see the following command is being executed. Note the double quotes "" after the -s parameter.

```
"C:/Users/Rik/AppData/Roaming/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer/omnisharp.cmd" -s ""C:\Users\Rik\Documents\Visual Studio 2015\Projects\WebApplication1\WebApplication1.sln"" -p 40765 -config "C:\Users\Rik\AppData\Roaming\Sublime Text 3\Packages\OmniSharp\PrebuiltOmniSharpServer\config.json" --hostPID 6380
```
Running the command results in the following error message. Could not find file 'C:\Users\Rik\Documents\Visual\'. 

![image](https://cloud.githubusercontent.com/assets/397160/7004594/fa165942-dc6d-11e4-92b4-cc0149a8d7b8.png)

The culprit is the following [line](https://github.com/OmniSharp/omnisharp-sublime/blob/master/lib/omnisharp.py#L117) that I can fix this on my own computer by removing the double quotes concatenation, but I'm unsure if this will continue to work on other machines as I am not a python programmer. 

Kind Regards,

Rik

**Comment by jchannon** [comment]
Merged PR
