### ISSUE TITLE
No solution file

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/omnisharp-sublime#154]
Can this plugin be used without a solution file? I used the yeoman generator for the project which it does not come with one. When I try to show the output console for omnisharp, nothing comes up. I am guessing this might be due to not have a solution file? Thanks

**Comment by jchannon** [comment]
The yeoman generator creates vnext apps. You can use this plugin but you
will manually have to clone the Roslyn branch into the sublime packages
folder

**Comment by jrock2004** [comment]
I git clone master, so when I switch what changes? Do I not have to specify a solution file?

**Comment by jchannon** [comment]
We have a roslyn branch that will work on aspnet vnext apps. The master
branch won't.

**Comment by jrock2004** [comment]
Ok so this is what I did

``` bash
[jcostanzo@punisher OmniSharp (master)]$ git checkout roslyn
Branch roslyn set up to track remote branch roslyn from origin.
Switched to a new branch 'roslyn'
[jcostanzo@punisher OmniSharp (roslyn)]$ git submodule update --init --recursive
[jcostanzo@punisher OmniSharp (roslyn)]$ ./build.sh 
./build.sh: line 3: cd: OmniSharpServer: No such file or directory
MSBUILD: error MSBUILD0003: Please specify the project or solution file to build, as none was found in the current directory.
```

**Comment by jchannon** [comment]
You don't need to do the build and sub module update. Close sublime. Reopen
and you should be ok. You may have to chmod +x on
PrebuiltOmnisharpServer/OmniSharp if you are on OSX

**Comment by jrock2004** [comment]
ok, so I re-open sublime and still when I click anything in the omnisharp menu window nothing comes up

``` bash
[jcostanzo@punisher PrebuiltOmniSharpServer (roslyn)]$ pwd
/Users/jcostanzo/Library/Application Support/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer
[jcostanzo@punisher PrebuiltOmniSharpServer (roslyn)]$ ls -l
total 16
drwxr-xr-x  4 jcostanzo  staff  136 Apr  7 13:32 approot
-rwxr-xr-x  1 jcostanzo  staff  626 Apr  7 13:32 omnisharp
-rw-r--r--  1 jcostanzo  staff  165 Apr  7 13:32 omnisharp.cmd
```

**Comment by jchannon** [comment]
As I said you might have to run chmod +x omnisharp. This file is called
when a csharp file is activated in sublime to start the omnisharp server.
You will see mono sgen processes in activity monitor

**Comment by jrock2004** [comment]
Ok so I open the activity monitor and it seems like it still wants a solution file

``` bash
omnisharp plugin_loaded
project file found
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "/Users/jcostanzo/Library/Application Support/Sublime Text 3/Packages/OmniSharp/listeners/server_runner.py", line 12, in on_activated
    omnisharp.create_omnisharp_server_subprocess(view)
  File "/Users/jcostanzo/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 180, in create_omnisharp_server_subprocess
    solution_path = current_solution_filepath_or_project_rootpath(view)
  File "/Users/jcostanzo/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/helpers.py", line 39, in current_solution_filepath_or_project_rootpath
    raise ValueError('Please specify a path to the solution file in your sublime-project file or delete it')
ValueError: Please specify a path to the solution file in your sublime-project file or delete it
```

**Comment by jchannon** [comment]
If it's a vnext project please delete your .sublime-project file

**Comment by jrock2004** [comment]
ok that did it. Now on to my next issue why it cannot see mono. Its there cause I can run the server so I need to investigate that for now. Thanks

**Comment by jchannon** [comment]
No probs. I have updated the readme on the roslyn branch.

If you installed mono via homebrew you need to expand the path in the
omnisharp file. Take a look at the omnisharp file in the master branch and
use that. I need to make them the same across both branches

**Comment by jrock2004** [comment]
Here is the error

``` bash
System.Exception: Unable to locate project.json
  at Microsoft.Framework.Runtime.DefaultHost.Initialize (Microsoft.Framework.Runtime.DefaultHostOptions options, IServiceProvider hostServices) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.DefaultHost..ctor (Microsoft.Framework.Runtime.DefaultHostOptions options, IServiceProvider hostServices) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.ApplicationHost.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

Here is the omnisharp file

``` bash
#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#export SET KRE_APPBASE="$DIR/approot/packages/OmniSharp/1.0.0/root"
export PATH=$PATH:/usr/local/bin

exec "$DIR/approot/packages/kre-mono.1.0.0-beta3/bin/klr" --appbase "$KRE_APPBASE" Microsoft.Framework.ApplicationHost omnisharp "$@"
```

I think I must have changed something wrong. I noticed that in master it shows .exe which would not work for me

**Comment by jchannon** [comment]
As long as you only appended the path it should be ok. I'll pass you over
to @markrendle as I don't really use this branch

**Comment by jrock2004** [comment]
Here is the full error from plugin output

/Users/jcostanzo/Library/Application Support/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer/approot/packages/kre-mono.1.0.0-beta3/bin/klr: line 14: exec: mono: not found

**Comment by jrock2004** [comment]
@markrendle any thoughts on this issue?

**Comment by markrendle** [comment]
What version of Mono are you running?

**Comment by nosami** [comment]
@jrock2004 try increasing your ulimit

**Comment by jrock2004** [comment]
Here is my out put from getting version

``` bash
Mono JIT compiler version 3.12.1 (tarball Tue Mar 17 15:03:14 GMT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by nosami** [comment]
@jrock2004 http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks

**Comment by jrock2004** [comment]
Looking now. Will let you know

**Comment by jrock2004** [comment]
@nosami , this linked helped me out and it solved my issue. http://docs.basho.com/riak/latest/ops/tuning/open-files-limit/#Mac-OS-X

**Comment by jeremejevs** [comment]
> If it's a vnext project please delete your .sublime-project file

@jchannon Is there a way to keep `.sublime-project`? It's useful for other things.
