### ISSUE TITLE
omnisharp script file not included in 1.9.1 in osx

### ISSUE THREAD

**Issue by rickyah** [OmniSharp/omnisharp-sublime#156]
I've updated Omnisharp to v1.9.1 using Package Control under OSX Yosemite (v10.10.2) and got a `FileNotFound` exception on load.

The reason seems to be that the PrebuiltOmniSharpServer folder does not contains [the bash script file 'omnisharp'](https://github.com/OmniSharp/omnisharp-sublime/blob/master/PrebuiltOmniSharpServer/omnisharp) that I think runs the OmniSharp server for osx
The exception originated in the file [OmniSharpSublime.py:22](https://github.com/OmniSharp/omnisharp-sublime/blob/master/OmniSharpSublime.py#L22)

I've solved the issue just copying manually that to the folder PrebuiltOmniSharpServer, and now everything seems to work fine.

**Comment by sksea** [comment]
Updating was bugged for me too. Resolved by removing the package and installing again through package manager-- worth a try.

**Comment by jchannon** [comment]
Tried it on my test VM and it seems to be there after upgrading from 1.9.0 to 1.9.1. 

I think for future upgrades I may need to put in the notes to restart Sublime after upgrades

**Comment by rickyah** [comment]
I had restarted sublime text 3 after updating. Anyway, I've tried it at home and the installation worked flawlessly so I've just reinstalled the omnisharp package at works, and everything went ok.  
I don't know why It gave me an error when installing at my work station but I'm glad to see is a "not working on my machine" problem :+1:
