### ISSUE TITLE
Ship both vnext server and original server

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-sublime#159]
There is a server for traditional solution based apps and another server for vnext apps.

At the moment we are maintaing 2 branches and this is becoming cumbersome and leading to mis information being spread.

We need a setting either in the plugin or via a sublime-project file so when a folder/project is loaded in Sublime it knows which server to start up.

That way we can focus on one branch to get features in.  Currently there is one feature in the Roslyn branch (code format on `;` press) that won't work in the original server so we may have to do something around that and there are also many features in the original server/master branch that wont work for vnext apps but I think users can accept that as long as they know vnext support is alpha

**Comment by coderangerdan** [comment]
Please, please, please. I can only edit non-roslyn, but only build roslyn apps on Mac ... unless I mess about which I would presume gets overwritten each time Omnisharp Sublime Package is updated.

**Comment by robbert229** [comment]
I am currently working on a solution to this, and sometime this week there should be an update containing both roslyn and original.

**Comment by tim241** [comment]
Closing due to having outdated information.
