### ISSUE TITLE
No Error/Warning Feedback in 1.9.1 while editing

### ISSUE THREAD

**Issue by richvreeland** [OmniSharp/omnisharp-sublime#160]
I just got the autoupdate (1.9.1) to omnisharp, and I'm getting this error. The server seems to do builds fine, but there is no error feedback while editing.

`
======== response ========
 true
file added to project
True
======== end ========
======== response ======== 
 response is empty
handling Errors
no data
======== end ========
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 312, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/r/Library/Application Support/Sublime Text 3/Packages/User/ShowFilenameInStatus.py", line 5, in on_activated_async
    filename = os.path.split(view.file_name())[1]
  File "./posixpath.py", line 106, in split
AttributeError: 'NoneType' object has no attribute 'rfind'`

**Comment by jchannon** [comment]
Error feedback is now done with squiggles, if you place your cursor over
the squiggle you will get a popup error. You can show the window by turning
this setting on

https://github.com/OmniSharp/omnisharp-sublime/blob/master/OmniSharpSublime.sublime-settings#L6

**Comment by richvreeland** [comment]
ah! thank you.
