### ISSUE TITLE
"omnisharp_onsave_showerrorwindows" shows errors every time an error is detected instead of on save.

### ISSUE THREAD

**Issue by richvreeland** [OmniSharp/omnisharp-sublime#161]
1.9.1 ... With "omnisharp_onsave_showerrorwindows" set to true, the error window pops up every time an error is detected while editing, instead of on save only.

**Comment by jchannon** [comment]
That's because code checks are run every time the file is modified hence
why this is false by default

**Comment by richvreeland** [comment]
i see. well you might want to change "onsave" to something more appropriate then ;)

is there any chance of keeping an option with the old behavior? i quite liked getting the error window only showing up on save.

**Comment by jchannon** [comment]
I'm open to it. Fancy sending a PR?

**Comment by karlgluck** [comment]
The fix is pretty easy, add a not-dirty check in `syntax.py` line 83 to this:

```
                if bool(helpers.get_settings(self.view,'omnisharp_onsave_showerrorwindows')) and not self.view.is_dirty():
```

I'd send a PR but my branch is pending another change.

**Comment by andzdroid** [comment]
+5 for old behaviour. Now every time I take a pause while typing, the error checker kicks in, the info panel pops up and resizes the editor window size. Editing code towards the bottom of the file is a nightmare because it is constantly adjusting height and therefore the code and cursor position.

**Comment by nosami** [comment]
![sublime-errors](https://cloud.githubusercontent.com/assets/667194/7163655/1c0c7924-e393-11e4-8a13-1aa51afd7c3f.gif)

Looks ok to me.

**Comment by andzdroid** [comment]
Probably because I have `omnisharp_onsave_showerrorwindows` set to true.

The name of the setting doesn't actually describe the setting apparently, so that's confusing

But I don't want to just set it to false, because I want to see the error window with a list of errors.

**Comment by karlgluck** [comment]
@andzdroid Yeah that was my change. Sorry about that! The one-liner I posted above will fix it. I'll try to get a PR in but our company's branch is starting to diverge.

**Comment by nosami** [comment]
Ah, ok. I tried setting `omnisharp_onsave_showerrorwindows ` to true. The error window doesn't show up at all for me any more :)

**Comment by jchannon** [comment]
@karlgluck I'm wondering whether it should go back to how it was so it only does the codecheck when the file is saved rather than every time the file is modified. Might keep things simpler?

**Comment by jchannon** [comment]
So I've changed the code to only do code checks when the file is saved on my local machine. This kind of works. The problem seems to be as described in #162 in that when I request /codecheck and /addtoproject when a file is saved the requests/responses seem to be cancelling each other out. My suspicions are a thread issue. If anyone fancies investigating this more clone this branch https://github.com/OmniSharp/omnisharp-sublime/tree/threadingissue I'm hoping @Jetski5822 and hos threading skills can help us

**Comment by Jetski5822** [comment]
@jchannon issued pull request.

**Comment by tim241** [comment]
Closing due to having outdated information.
