### ISSUE TITLE
IndexError('list index out of range',) in 1.9.1

### ISSUE THREAD

**Issue by hgranholm** [OmniSharp/omnisharp-sublime#164]
Hello!

The new features in this build sound excellent, but I get this error now:
RAISE_OMNI_SHARP_LAUNCHER_EXCEPTION:IndexError('list index out of range',)

I do have a project folder & solution. Also the omnisharp launcher script seems to have disappeared completely? Perhaps you moved it elsewhere, or alternatively the chmod is not working 100% optimally :-)

**Comment by Cygnusfear** [comment]
Having the same list index out of range error here with a Unity project. Assistance is greatly appreciated!

**Comment by michaelblyons** [comment]
I get this, too. OSX Yosemite.

**Comment by Cygnusfear** [comment]
I've managed to get rid of this by completely removing the OmniSharp plugin
and reinstalling it.

**Comment by michaelblyons** [comment]
@Cygnusfear: That worked for me, too.

When I went to add my settings to the User settings for O#Sublime, I discovered that there was a `omnisharp_server_config_location` option in there with a path to a `config.json` in the O# package folder. @hgranholm: Do you have that line in yours, or did my reinstall add it?

**Comment by hgranholm** [comment]
@michaelblyons I do also have that path in the OmniSharp user settings.

Yeah I thought about clean installing too, but figured it might be useful to first investigate this state. I guess I'll just reinstall now, thanks :-)

**Comment by hgranholm** [comment]
Yes, reinstall did it. Love the new tooltip feature!

Not sure if I should close the ticket or not, so I'll just leave it open.
