### ISSUE TITLE
Super+N Keymapping conflicts with default in OSX

### ISSUE THREAD

**Issue by radium-v** [OmniSharp/omnisharp-sublime#170]
Hi,

[This line](https://github.com/OmniSharp/omnisharp-sublime/commit/b73654d6318d6af28edc7fe6dd2f17615222fbfa#diff-63fb6b816ec19fd3fb71843f0583eca6R17) overrides the default OSX keymapping for "New File".

**Comment by jchannon** [comment]
Fixed and new version released as of https://github.com/OmniSharp/omnisharp-sublime/commit/e6a49a1a85abc1561e5eebf212ea3ae6a4c4d762

Thanks :smile:
