### ISSUE TITLE
Switch from kvm to dnx

### ISSUE THREAD

**Issue by jrock2004** [OmniSharp/omnisharp-sublime#171]
With the new change that k has been renames to dnx, the plug in is not working cause its looking for the .k directory

``` bash
[ERROR:OmniSharp.AspNet5.AspNet5ProjectSystem] The specified runtime path 'default' does not exist. Searched locations /Users/jcostanzo/.k/runtimes/kre-mono.default
/Users/jcostanzo/.k/packages/KRE-Mono.default
/Users/jcostanzo/.kre/runtimes/kre-mono.default
/Users/jcostanzo/.kre/packages/KRE-Mono.default
[INFORMATION:OmniSharp.AspNet5.AspNet5ProjectSystem] No default KRE found
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/jcostanzo/Development/CarTrackerApplication'
Solution has finished loading
```

I am using the roslyn branch now since I am using asp5 mvc 6

**Comment by nosami** [comment]
This was fixed in omnisharp-roslyn some time back.... just needs the binaries updating in omnisharp-sublime.

**Comment by jrock2004** [comment]
I just pulled this branch tonight on this machine. Is there some other settings I may be missing

**Comment by nosami** [comment]
No...you're not missing anything. Omnisharp-sublime doesn't have the latest binaries bundled with it. You could attempt to do it yourself until omnisharp-sublime is fixed. https://github.com/OmniSharp/omnisharp-sublime/tree/master/PrebuiltOmniSharpServer

**Comment by jrock2004** [comment]
You mean using this omnisharp file? https://github.com/OmniSharp/omnisharp-sublime/blob/master/PrebuiltOmniSharpServer/omnisharp

**Comment by nosami** [comment]
No.... you would need to build [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) and copy the output to https://github.com/OmniSharp/omnisharp-sublime/tree/roslyn/PrebuiltOmniSharpServer

Or you could try Atom................. it has the latest binaries bundled and is frequently updated right now.

**Comment by jrock2004** [comment]
What is sublime losing the game and everyone is switching to atom?

**Comment by nosami** [comment]
Sublime would be fine if it had the binaries updated ;)

**Comment by jrock2004** [comment]
So I think I am trying to build this right 

``` bash
➜  OmniSharp git:(roslyn) ./build.sh 
./build.sh: line 3: cd: OmniSharpServer: No such file or directory
MSBUILD: error MSBUILD0003: Please specify the project or solution file to build, as none was found in the current directory.

```

**Comment by nosami** [comment]
I just meant that there is a lot of momentum behind omnisharp-atom right now https://github.com/OmniSharp/omnisharp-atom/pulse/daily

**Comment by nosami** [comment]
That doesn't look like the output from this build.sh https://github.com/OmniSharp/omnisharp-roslyn/blob/master/build.sh

**Comment by jrock2004** [comment]
Yeah I see its a different repo. Its seems that the file you are pointing to though is trying to setup kvm. Am I missing something?

**Comment by nosami** [comment]
It sets up kvm if it's not already installed. Then it builds and tests omnisharp-roslyn.

**Comment by jrock2004** [comment]
But I thought MS has renamed kvm to dnx as its no longer using that. Or did I miss something.

**Comment by ctolkien** [comment]
Current "stable" branch is still using k* naming.

**Comment by nosami** [comment]
ok.... omnisharp-roslyn needs beta3 / kvm to build.... but once it's built, you can use it against dnx solutions.

**Comment by jrock2004** [comment]
I just switched to atom and will just start using that :)
