### ISSUE TITLE
Readme update (setup for Unity)

### ISSUE THREAD

**Issue by zero3growlithe** [OmniSharp/omnisharp-sublime#173]
When I first tried to configure OmniSharp for Sublime with Unity I had a problem with the OmniSharpServer closing with not-responding error. After few months I figured out that although I specified the path to solution file explocitly in the project settings OmniSharp needs the workspace folder set to the whole Unity Project folder, and in my case I set it to Assets folder instead to avoid filling Go-to-anything with unnecessary files.
I think it is worth mentioning in the readme that specyfying the .sln file is not enough for OmniSharp to work properly but it needs the whole project like VS.

**Comment by jchannon** [comment]
Please feel free to update the README :smile: :+1:
