### ISSUE TITLE
Sort Warnings/Errors in Compile Log by Line

### ISSUE THREAD

**Issue by WastedMeerkat** [OmniSharp/omnisharp-sublime#177]
Currently it seems that the warnings/errors are just listed in the order the compiler finds them; however, I think it would be useful to be able to sort them by the line where the warning/error is found. It would also be nice to be able to double click an error/warning and go to the line it appears on, but that seems to be covered already by #130. If it's too complex to implement some sort of ascending/descending sort UI element to the output log, it could be implemented as a user preference and sorted somewhere before it's printed out to the log. Thanks!

**Comment by jchannon** [comment]
Check the latest release
