### ISSUE TITLE
Is there a plan for use omnisharp-roslyn?

### ISSUE THREAD

**Issue by fishg** [OmniSharp/omnisharp-sublime#184]
I found some omnisharp-roslyn api is faster than omnisharp-servers,eg. find usage is obviously faster after first active. Otherwise omnisharp-servers is no longer get support.
I have some test , I use omnisharp-sublime with  omnisharp-roslyn on my OS X.No big problem be found,but if use omnisharp-roslyn,there is some more install steps needed.

**Comment by jchannon** [comment]
There is another branch that uses omnisharp-roslyn but only for dnx
applications. The plan was to wait for omnisharp-roslyn to have all the
features omnisharp-server had then move over. I'm not sure if it has
everything yet? If it has we can start moving it over. One thing I don't
think it has is the Fix Usings command. Might be worth noting all the
features the plugin has and tick them off against omnisharp-roslyn has.
Maybe @nosami could help confirm the features

**Comment by fishg** [comment]
@jchannon  Thanks for your explain. Looks like not support fix using yet. I will have more test in daily use.

**Comment by davidfowl** [comment]
@fishg @jchannon Refactorings wise, omnisharp-roslyn will soon have all of the features VS has https://github.com/OmniSharp/omnisharp-roslyn/tree/magic. The MSBuild support isn't quite there yet

**Comment by fishg** [comment]
@jchannon @davidfowl 
I create a roslyn branch on my fork and dependent on omnisharp-roslyn/tree/magic.On my Unity3D project,everything looks fine.And I found these features loos:
* Reload solution
* fixcodeissue
* fixusings
* getoverridetargets
* codecheck do not show fix code advise
* removefromproject
* addtoproject
