### ISSUE TITLE
System.Windows.Forms

### ISSUE THREAD

**Issue by IBIT-ZEE** [OmniSharp/omnisharp-sublime#185]
Why Autocomplete/intellisense fails when I try to use  System.Windows.*

for example : using System.Windows.Forms

**Comment by nosami** [comment]
Did you add a reference to System.Windows.Forms in your project?

**Comment by IBIT-ZEE** [comment]
Thanks... 
This is a single file program... 
I have no project file...

Some assemblies are recognized by intellisense... like collections, io, link, etc.
but there are a lot missing... like Windows...

Can I had a reference to an assembly in a single code file... like my test.cs
or if I create a app.config onmisharp-sublime add references to assemblies automagically,,,

Thanx

**Comment by jchannon** [comment]
Not really, if you add a reference you are modifying a csproj. If you dont
have one of those then it wont work.

Just create an empty solution in Xamarin/VS

**Comment by nosami** [comment]
That's not quite true... omnisharp-server will work if you just have a bunch of cs files and dll files in a folder without any project files. It will reference every dll that it finds. 

Although then you are on your own when it comes to compiling - xbuild/msbuild aren't going to work. 

You'd need to fallback to csc/mcs etc

**Comment by IBIT-ZEE** [comment]
good info nosami... i'll try that... 
maybe with symbolic links we can some funcionaity,,,
