### ISSUE TITLE
Styling new warning/error panel

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-sublime#186]
@fishg recently added a new panel for errors and warnings. It would be nice to style it if possible to match that of the build output panel.

**Comment by fishg** [comment]
original output panel support syntax file:
`output.set_syntax_file("Packages/Syntax/Syntax.tmLanguage")`
Your mean this?

**Comment by fishg** [comment]
@jchannon I created a patch commit about this.

**Comment by jchannon** [comment]
Nice, is that #187

**Comment by fishg** [comment]
@jchannon Yes, [#187](https://github.com/OmniSharp/omnisharp-sublime/pull/187) is patch for panel message's syntax.

**Comment by jchannon** [comment]
Is it the same tmlanguage file or copy/paste as the build output ?

**Comment by fishg** [comment]
@jchannon I copyed from build output,but clean some unused field and add output message syntax regular.

**Comment by jchannon** [comment]
Brilliant!

I'll try and take a look a bit later.

Thanks =)

**Comment by fishg** [comment]
@jchannon Ok.If need I can clean more unused field.

**Comment by jchannon** [comment]
I think we might need to change the regex as the errors and warning colours dont quite match. Might need to speak nicely to @maliayas 

Here's the build output 

![screen shot 2015-06-18 at 10 01 45](https://cloud.githubusercontent.com/assets/105126/8227780/d1495416-15a1-11e5-943f-c2ead1432f4a.png)


This is the warning/error colours from code checks

![screen shot 2015-06-18 at 10 01 22](https://cloud.githubusercontent.com/assets/105126/8227789/da7a90e0-15a1-11e5-9726-ae050fd4b24a.png)
![screen shot 2015-06-18 at 10 01 02](https://cloud.githubusercontent.com/assets/105126/8227790/da7d2440-15a1-11e5-93bc-059692121482.png)

**Comment by fishg** [comment]
Ok,I will try use the same color used on build output.

**Comment by fishg** [comment]
@jchannon Looks like outputpanel can not add a custom color_scheme file.My points is use color_scheme with sublime theme.

**Comment by fishg** [comment]
@jchannon Updated.

**Comment by jchannon** [comment]
Seems to be the same colours for me

**Comment by fishg** [comment]
Which color scheme you use?
On my version look like fine.
![qq20150619-1](https://cloud.githubusercontent.com/assets/1423545/8246529/771679c0-1672-11e5-9590-93241f475a49.png)
![qq20150619-2](https://cloud.githubusercontent.com/assets/1423545/8246530/77202ed4-1672-11e5-9423-83d93da0d036.png)

**Comment by jchannon** [comment]
I use 
```
"color_scheme": "Packages/Theme - itg.flat/itg.Monokai.tmTheme",
"theme": "itg.flat.dark.sublime-theme",
```

**Comment by fishg** [comment]
I found the problem.In my evn,sublime linter will auto fix color scheme,if I use the same scheme as your,my sublime will auto change to : 
`"color_scheme": "Packages/User/SublimeLinter/itg.Monokai (SL).tmTheme"`
I will find an other way to fix.

**Comment by jchannon** [comment]
I was trying to see how the build output works but I can see that only seems to set the syntax file so I'm not sure what the difference is

**Comment by fishg** [comment]
I found in BuildConsole.sublime-settings configured a color scheme file.But I don't find a way set color scheme for output panel util now.

**Comment by fishg** [comment]
@jchannon My new commit fixed color scheme problem.

**Comment by fishg** [comment]
Can close?
