### ISSUE TITLE
Code actions add extra carriage return characters (Windows)

### ISSUE THREAD

**Issue by dsmeathers** [OmniSharp/omnisharp-sublime#189]
![image](https://cloud.githubusercontent.com/assets/12965761/8259315/77eff84e-16b3-11e5-8325-65ad7cd7b8f7.png)

I'm not able to test this on Mac or Linux but I get extra carriage return characters under Windows. After saving and reopening the file I have two new lines at the end of each line.

**Comment by jchannon** [comment]
Have a play with this settings - https://github.com/OmniSharp/omnisharp-sublime#format-document-settings

:hand: :five:
