### ISSUE TITLE
Disable method override popup

### ISSUE THREAD

**Issue by bdjones** [OmniSharp/omnisharp-sublime#193]
Immediately after typing the word 'override' in a class, the Sublime command palette pops up with a list (albeit incomplete, more often than not) of functions that I can override. And anything I type after the word 'override' is written in the command palette text field.

Maybe some people are finding that handy, but I personally find it extremely annoying. I type 'override', then I have to hit Escape to close the command palette, then I hit Space and the command palette opens up again, and then I have to hit Escape again to finally be able to type in what I want to type.

Is there any setting to disable this feature?

Sorry for the whining :) These little quality of life issues really get to me sometimes! :D

**Comment by HalfVoxel** [comment]
I can add that this also shows up inside comments which is a bit more annoying.

**Comment by aMoniker** [comment]
This is super annoying. I also want the option to remove it.

**Comment by invicticide** [comment]
I submitted a pull request #195 that adds a config setting to disable this feature.

**Comment by HalfVoxel** [comment]
Is there any reason the override popup doesn't use the same autocomplete popup as the rest of the code?

**Comment by tim241** [comment]
Closing due to having outdated information.
