### ISSUE TITLE
When I save, error show up. is this normal?

### ISSUE THREAD

**Issue by phongyewtong** [OmniSharp/omnisharp-sublime#198]
When I save, error show up. is this normal?
![screen shot 2015-09-23 at 5 59 23 pm](https://cloud.githubusercontent.com/assets/4919605/10042251/da31dfea-621c-11e5-92e8-0def76fb9175.png)

**Comment by jchannon** [comment]
Yes its telling you it doesn't have loaded assemblies/namespaces

**Comment by phongyewtong** [comment]
Thanks! I just figured out I need to open the .sublime-project file before double clicking on a script.
