### ISSUE TITLE
override autocompletion bug

### ISSUE THREAD

**Issue by maur1th** [OmniSharp/omnisharp-sublime#199]
Doesn't autocomplete in the current class: https://youtu.be/p3xH3aj35Ls
ST version 3095 on Fedora 22

**Comment by sagood** [comment]
/OmniSharp/Overrides/OverrideHandler.cs from line 111
should be modified like this:

var firstNode = 
      typeDeclaration.Children.FIrst();

script.InsertAfter
(     node        :  firstNode
    ,  newNode :  memberDeclaration);

**Comment by tim241** [comment]
Closing due to having outdated information.
