### ISSUE TITLE
Wish to help maintaining

### ISSUE THREAD

**Issue by zalenix** [OmniSharp/omnisharp-sublime#203]
Hi, I'm a relatively nee software developer with about a year experience with coding c# with Visual Studio 2013. I am looking for other ways to compile and debug c# and that search brought me here. I am interested to help maintaining aa best as I can. Please let me know how I can help.

**Comment by jchannon** [comment]
Hi, if you want to have a go at fixing any of the issues and submitting PRs then I can take a look and we can take it from there?

**Comment by robbert229** [comment]
@zalenix Are you still looking to help?
