### ISSUE TITLE
Regarding Maintainer Need

### ISSUE THREAD

**Issue by robbert229** [OmniSharp/omnisharp-sublime#204]
In the Omnisharp meeting I stated my intent to help maintain and continue development on this project. In order to get PRs through and for getting feedback who should I be pinging? @david-driscoll @jchannon

**Comment by david-driscoll** [comment]
You can ping me, I'm not setup to test sublime at the moment, but I could get it configured I'm sure.  I'm not sure about @jchannon, so I'll leave that up to him.

**Comment by robbert229** [comment]
Alright, in addition I have some ideas for needed changes, and improvements. Should I be talking to you and @jchannon about them? (One of these improvements being #159)

@david-driscoll

**Comment by david-driscoll** [comment]
I say take the package forward, improvements, features, bug fixes, whatever
you think will be good for the package.

**Comment by jchannon** [comment]
Added you as a contributor with write access and merged the PR. Have fun

**Comment by karlgrz** [comment]
I am set up to test omnisharp-sublime (and have actually gone back to using it more frequently than atom) so I'd be happy to help test, as well. Perhaps I will get some time freed up in the near future to start fixing bugs, too.

**Comment by robbert229** [comment]
That sounds great, last night I managed to get the plugin to support both omnisharp-server and omnisharp-roslyn. Just cleaning it up before I ask someone to test/review.

**Comment by jchannon** [comment]
@robbert229 have you removed me as an owner of this repo? I no longer seem to have admin rights.  Can you add me back please? Thanks

**Comment by robbert229** [comment]
I didn't remove you ( that would be a scumbag move ), and just added you.

**Comment by jchannon** [comment]
Thanks. Not sure what happened there :smile:
