### ISSUE TITLE
Failing to communicate to CheckReadyStatus

### ISSUE THREAD

**Issue by Stephn-R** [OmniSharp/omnisharp-sublime#211]
Error:

```
HTTPConnectionPool(host='localhost', port=50901): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))
```

**Comment by robbert229** [comment]
Can you give me some more details? Like os, did you install via package control, or cloning the repo, etc.

**Comment by Stephn-R** [comment]
OS: El Capitan on Mac Air 13"

- Installed via Package Control
- Mono installed using `brew cask install mono-mdk`

Node Version: v5.4.1
Npm Version: 3.3.12
Mono Version: 4.2.1

**Comment by Stephn-R** [comment]
also tested in Atom (straight install from Atom Package Installer) --> No issues

**Comment by robbert229** [comment]
Also, could you pastebin the log from sublime? 

Omnisharp-atom and omnisharp-sublime are two completely different plugins written in different languages,  they both just communicate with the same backend via post requests (omnisharp-roslyn or omnisharp-server(legacy)).

**Comment by jounisuominen** [comment]
I also got this when I updated Sublime to 3103. Paste: http://pastebin.com/ZLgEuTK3

**Comment by jounisuominen** [comment]
Ok I just updated Mono to latest 4.2.2.30-x86 and it started working...

**Comment by Murriouz** [comment]
Same here on Sublime 3113.

Update Mono doesn't work for me.

Pastebin:  http://pastebin.com/cX0XQPG7

**Comment by xdegtyarev** [comment]
Yup, same here:
https://gist.github.com/xdegtyarev/298844b108309a2777dd46f7a877d0cb
Update Mono to 4.2.1 and rebuilt - same issue

**Comment by nfantone** [comment]
Something similar here:

```
Traceback (most recent call last):
  File "/Users/nfantone/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 143, in <lambda>
    sublime.set_timeout(lambda:check_solution_ready_status(view), 5000)
  File "/Users/nfantone/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 183, in check_solution_ready_status
    get_response(view, "/checkreadystatus", ready_status_handler)
  File "/Users/nfantone/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 84, in get_response
    timeout = int(get_settings(view, 'omnisharp_response_timeout'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

On Mac OSX El Capitan, Sublime `3120` and latest omnisharp-sublime `1.9.6`.

**Comment by jaxuru** [comment]
I have the latest omnisharp-sublime (installed with package control) and the latest mono (`brew install mono` on Sierra, mono version 5.0.1.1) and I'm getting both @Stephn-R's original issue, and occasionally @nfantone's issue. Weirdly, Omnisharp works correctly regardless, and trying to manually start the server gives a message saying that the server is already running, and yet this error message still displays.
