### ISSUE TITLE
There is no Intellisense whatsoever in C#

### ISSUE THREAD

**Issue by leocrespo** [OmniSharp/omnisharp-sublime#214]
How can you possibly comment that this is a C# editor if there's no intellisense whatsover? 

http://d.pr/i/12NZq+

**Comment by robbert229** [comment]
That is not planned behavior. Could you post the sublime text logs, as well as some information on what system you are running?

**Comment by leocrespo** [comment]
Steps to reproduce: 
1) install sublime
2) install this package
3) open a single .cs and check if there's intellisense.

**Comment by robbert229** [comment]
Hmm, could you post the sublime text logs, as well some system information?

**Comment by leocrespo** [comment]
As if this would make any difference what version of mac os I am running

**Comment by robbert229** [comment]
It might, the plugin has platform specific binaries it calls. Also could you get me your version of mono?

**Comment by leocrespo** [comment]
Did you even try simulating the problem? Literally all you have to do is right click a .cs file, open with Sublime and you'll see that there's no intellisense.

**Comment by robbert229** [comment]
Yes, I have. And guess what, it works. That's why I need some basic information such as logs, and system information. I wan't to fix it, but without that information I can't actually do anything.

**Comment by leocrespo** [comment]
Im pretty sure it doesn't work, you probably have the .cs file opened as part of a project. I'm done with this thread, bye.
