### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by vladipus** [OmniSharp/omnisharp-sublime#220]
Is the project actually maintained now?

**Comment by robbert229** [comment]
Kind of... I am wanting to migrate to roslyn but last time I checked roslyn doesn't actually implement all of the features that omnisharp-sublime uses. This combined with my lack of time has prevented me from really maintaining it.

**Comment by vladipus** [comment]
Thank you for your response)

**Comment by robbert229** [comment]
Just a heads up @vladipus, now that dotnetcore is actually out and things are stabilizing I am expecting to invest a lot more time into this.

**Comment by vladipus** [comment]
Good luck with that!
