### ISSUE TITLE
Symbols with generics not recognized by syntax highlighter or Goto Symbol

### ISSUE THREAD

**Issue by jaxuru** [OmniSharp/omnisharp-sublime#221]
I'm using Omnisharp in sublime to edit Unity scripts and when I define a method like this:

`protected override void AttemptMove <T> (int xDir, int yDir)`

... the "protected" and "override" keywords get highlighted properly, but the "void", the name of the method, the generic, and the arguments are plain white, unhighlighted. Also, when I press command + R to bring up the Goto Symbol search bar, this method doesn't appear. Removing the generic from the definition allows syntax highlighting and symbol recognition to work properly.

I'm using Omnisharp v1.9.6 on Sublime Build 3114.

Thanks!

**Comment by tim241** [comment]
Closing due to having outdated information.
