### ISSUE TITLE
Connection Refused with url /checkreadystatus when using Unity and Sublime

### ISSUE THREAD

**Issue by jaxuru** [OmniSharp/omnisharp-sublime#228]
I know that this is similar to a couple of closed issues, but I tried what was suggested in those threads and I'm having no luck.

After opening my project in Unity, and after having created the `.sublime-project` file that points to the `.sln` file, I open the project in Sublime and open a `.cs` file to see if Omnisharp loads correctly. I get the following status message:

```
Omnisharp : Error talking to http://localhost:54200/checkreadystatus
```

The sublime console reads as follows:

```
======== request ======== 
 Url: http://localhost:54200/checkreadystatus 
 Data: {"buffer": "namespace UnityTest.Assets\n{\n    public class newclass\n    {\n\t\n    }\n}", "column": "2", "filename": "/Users/[username]/Dropbox/code/workspace/scratch/UnityTest/Assets/newclass.cs", "line": "5"}
HTTPConnectionPool(host='localhost', port=54200): Max retries exceeded with url: /checkreadystatus (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))
SublimeLinter: annotations activated: <builtin> 
```

I tried quitting the mono process, waiting, and retrying, I tried reinstalling mono, but I still get the same message. I have my `config.json` file in my `Packages/User/Omnisharp` folder, with that directory set in my Omnisharp user settings.

Random detail, in case it matters: when I search for `mono` in Activity Monitor, the process is actually called `mono-sgen` .

**Comment by L4D15** [comment]
I'm having this problem as well. It was working just a couple days back :-(

**Comment by jaxuru** [comment]
I fixed this issue by going into the `/lib/omnisharp.py` file and changing the timeout maximum from 5000 to 10000.

**Comment by L4D15** [comment]
Tried changing the timeout. Still having this issue :-(

**Comment by L4D15** [comment]
Updating mono throughout home-brew seems to have fixed it.

**Comment by charlietran** [comment]
Uninstalling the mono that I had gotten from mono-project.com and then reinstalling mono via homebrew also fixed this issue for me
