### ISSUE TITLE
Stop Telling Me How to Write Code

### ISSUE THREAD

**Issue by Zeman97** [OmniSharp/omnisharp-sublime#232]
Just setup sublime with OmniSharp and I keep getting errors about capitalization or naming convention which are already annoying, but the unforgivable one was that I use camel casing for field names, even though by Microsoft's guidelines, all public members are to use Pascal casing.

I added ".*" to the IgnoredCodeIssues list and I'm still getting the same warnings.

All I want is the auto complete for convenience.

(Also apologies if this is not the fault of OmniSharp, I just don't know what else it could be)

Thanks

**Comment by LuizThiagoDev** [comment]
Same here =(

**Comment by tim241** [comment]
No useful feedback/comment has been provided,

Closing
