### ISSUE TITLE
Does this project is dead, why it doesn't solve issues and not updated for 3 years?

### ISSUE THREAD

**Issue by AuthorProxy** [OmniSharp/omnisharp-sublime#238]

**Comment by AngryAnt** [comment]
The clue is in the first two lines of README.md :)

> Help Required
> Looking for a maintainer. If you'd like to help manage this plugin please file and issue

Not that there are a lot of pending pull requests either.

**Comment by tim241** [comment]
Alright, I'm the new maintainer for a few months now and finally got omnisharp-roslyn updated.

so this info is outdated!

Closing
