### ISSUE TITLE
Project maintenance request

### ISSUE THREAD

**Issue by tim241** [OmniSharp/omnisharp-sublime#239]
Can I maintain this project?

I already have a few patches:
https://github.com/tim241/omnisharp-sublime/tree/tim241/submodule-patch
https://github.com/tim241/omnisharp-sublime/tree/tim241/python-fix
https://github.com/tim241/omnisharp-sublime/tree/tim241/md-patch

branch with all patches applied:
https://github.com/tim241/omnisharp-sublime/tree/tim241/patched

I'm currently waiting for a fix from GitVersion (then I can compile the newest omnisharp-roslyn and fix stuff if it doesnt work)

**Comment by theredfish** [comment]
Hello @tim241,
Is there any news about your ask (private message or anything like that)?

**Comment by tim241** [comment]
@theredfish no, nothing sadly.

**Comment by theredfish** [comment]
Maybe @jchannon can help or contact someone? :)

**Comment by jchannon** [comment]
Bat signal has been put out. Hold tight

**Comment by filipw** [comment]
@tim241 I added you as admin to this repo - welcome! 🚀🎉 thanks @jchannon

**Comment by tim241** [comment]
thank you @filipw  @jchannon and @theredfish !
