### ISSUE TITLE
Can't ignore "Code Issue"

### ISSUE THREAD

**Issue by Zeredan** [OmniSharp/omnisharp-sublime#242]
In the config.json configuration, I wrote this:

`"^Comparison of floating point numbers can be unequal due to the differing precision of the two values.*"`

And after that, my code wouldn't load in for OmniSharp. Maybe it's just with me, or I mistyped something, but can somebody help me out?

**Comment by tim241** [comment]
I don't understand what you've tried, please explain it/post the full configuration file(and the path of it).
Also please explain what you're trying to do.

**Comment by Zeredan** [comment]
` C:\Users\vassz\AppData\Roaming\Sublime Text 3\Packages\OmniSharp\PrebuiltOmniSharpServer\config.json `

```
"IgnoredCodeIssues": [

     "^Keyword 'private' is redundant. This is the default modifier.$",
     ".* should not separate words with an underscore.*",
     "^Redundant argument name specification$",
     "^Convert to '.*' expre.",
     "^Use 'var' keyword$",
     "^Name should have prefix.",
     "^Redundant ToString.",
     "^Initializing field by default value is redundant$",
     "^Parameter can be IComparable$",
     "^Convert to constant.*",
     "^Convert to readonly*",
     "^Variable could be moved to a nested scope$",
     ".* Method never reaches its end or a 'return' statement.$",
     ".* should start with an upper case letter. \\(Rule 'Enum Members'\\)$"
 ],
```

**Comment by tim241** [comment]
Alright, omnisharp-server has been deprecated for a long time now,

I'm the new maintainer so I just updated omnisharp-roslyn(also removed omnisharp-server)

and it seems like you can't ignore code issues in omnisharp-roslyn yet: https://github.com/OmniSharp/omnisharp-roslyn/issues/301

**Comment by Zeredan** [comment]
> Alright, omnisharp-server has been deprecated for a long time now,
> 
> I'm the new maintainer so I just updated omnisharp-roslyn(also removed omnisharp-server)
> 
> and it seems like you can't ignore code issues in omnisharp-roslyn yet: [OmniSharp/omnisharp-roslyn#301](https://github.com/OmniSharp/omnisharp-roslyn/issues/301)
> 
> I'll most likely release a new version of omnisharp-sublime soon, need to fix a few things and test some more. But while you're at it, you can try the latest master.

I'm testing it, so far I had some technical problems installing it, but after a while, it just started working again. So this is not a problem, although warnings are not popping up. Which is not really the big thing, but I liked it in the older releases. Is it going to come back later on? Or removed completely?

**Comment by tim241** [comment]
I don't want to maintain a deprecated tool in this repo, so it's gone forever.

I did not change how warnings/errors work, the panel should pop up like usual.

**Comment by tim241** [comment]
Alright, I'll close this since this is not my issue.
