### ISSUE TITLE
이거 사용법좀...

### ISSUE THREAD

**Issue by hj666c2** [OmniSharp/omnisharp-sublime#244]
저거 보기는 했는데요. 제가 sublime text를 잘 못써서... 하는 방법을 잘 모르겠어요. 방법좀 알려주실 수 있나요?

(I saw, but I can't use sublime text well so I don't know how using this. Can you teach me?)

**Comment by tim241** [comment]
Alright, this issue isn't that great, I cannot read that language and do *NOT* want a rough translation.

Please change your language from sublime(or your system.) and post the actual English error.

Also please open a new issue for that.
