### ISSUE TITLE
RAISE_OMNI_SHARP_LAUNCHER_EXCEPTION

### ISSUE THREAD

**Issue by shanselman** [OmniSharp/omnisharp-sublime#73]
I am seeing this more and more

```
LAUNCH!!! C:\Users\scott_000\AppData\Roaming\Sublime Text 3\Packages\OmniSharp\launchers\omni_sharp_launcher.py
RAISE_OMNI_SHARP_LAUNCHER_EXCEPTION:FileNotFoundError(2, 'The system cannot find the file specified', None, 2)
```

on new installs. There isn't enough info in the error for someone to solve this. Config.json is there and the path is correct.

**Comment by gimmi** [comment]
Please consider launching python on windows by using the "python launcher":

https://www.python.org/dev/peps/pep-0397/

**Comment by jchannon** [comment]
We won't be needing an external python to launch in the future
