### ISSUE TITLE
After running code action, no cursor is present

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-sublime#93]
When you run a code action after selecting an action via `Alt+Enter` there is no cursor active to allow typing.  I'm guessing we need to set focus on the view after a code action is run

**Comment by dsmeathers** [comment]
I found that commenting out self.view.sel().clear() in OmniSharpRunCodeAction fixes this issue:

class OmniSharpRunCodeAction(sublime_plugin.TextCommand):
  def run(self, edit, args):
    region = sublime.Region(0, self.view.size())
    self.view.replace(edit, region, args['text'])
    #self.view.sel().clear()

**Comment by jchannon** [comment]
Cool!

Do you fancy doing a pull request?

**Comment by dsmeathers** [comment]
Well I've never used git before and only signed up to github to tell you about this one-liner... but sure why not!

Btw, omnisharp sublime is awesome, thank you :)

**Comment by jchannon** [comment]
No problem, welcome to the club! :smile:
