### ISSUE TITLE
errors connecting

### ISSUE THREAD

**Issue by gregoryyoung** [OmniSharp/omnisharp-sublime#96]
Mac install (from package) logs come up as:

project file is : /Users/greg/Code/EventStore/src/EventStore.sublime-project
solution_path:/Users/greg/Code/EventStore/src/EventStore.sln
omni_port:50476
LAUNCH!!! /Users/greg/Library/Application Support/Sublime Text 3/Packages/OmniSharp/launchers/omni_sharp_launcher.py
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
unknown include #documentation
start_omni_sharp_launcher:/Users/greg/Code/EventStore/src/EventStore.sln
exit_omni_sharp_launcher:/Users/greg/Code/EventStore/src/EventStore.sln
project file is : /Users/greg/Code/EventStore/src/EventStore.sublime-project
response: /Users/greg/Code/EventStore/src/EventStore.sln
request: http://localhost:50476/autocomplete
======== request params ======== 
 {"wordToComplete": "_", "WantReturnType": true, "column": "14", "WantSnippet": true, "filename": "/Users/greg/Code/EventStore/src/EventStore.Core.Tests/Helpers/MiniClusterNode.cs", "WantMethodHeader": true, "buffer": "using System;\nusing System.Diagnostics;\nusing System.IO;\nusing System.Linq;\nusing System.Net;\nusing System.Net.Sockets;\nusing System.Runtime.InteropServices;\nusing System.Threading;\nusing EventStore.Common.Log;\nusing EventStore.Common.Options;\nusing EventStore.Common.Utils;\nusing EventStore.Core.Authentication;\nusing EventStore.Core.Bus;\nusing EventStore.Core.Cluster.Settings;\nusing EventStore.Core.Messages;\nusing EventStore.Core.Services.Gossip;\nusing EventStore.Core.Services.Monitoring;\nusing EventStore.Core.Tests.Http;\nusing EventStore.Core.Tests.Services.Transport.Tcp;\nusing EventStore.Core.TransactionLog.Checkpoint;\nusing EventStore.Core.TransactionLog.Chunks;\nusing EventStore.Core.TransactionLog.FileNamingStrategy;\nusing EventStore.Core.Services.Transport.Http.Controllers;\n\nnamespace EventStore.Core.Tests.Helpers\n{\n    public class MiniClusterNode\n    {\n        public static int RunCount = 0;\n        public static readonly Stopwatch RunningTime = new Stopwatch();\n        public static readonly Stopwatch StartingTime = new Stopwatch();\n        public static readonly Stopwatch StoppingTime = new Stopwatch();\n\n        public const int ChunkSize = 1024*1024;\n        public const int CachedChunkSize = ChunkSize + ChunkHeader.Size + ChunkFooter.Size;\n\n        private static readonly ILogger Log = LogManager.GetLoggerFor<MiniClusterNode>();\n\n        public IPEndPoint InternalTcpEndPoint { get; private set; }\n        public IPEndPoint InternalTcpSecEndPoint { get; private set; }\n        public IPEndPoint InternalHttpEndPoint { get; private set; }\n        public IPEndPoint ExternalTcpEndPoint { get; private set; }\n        public IPEndPoint ExternalTcpSecEndPoint { get; private set; }\n        public IPEndPoint ExternalHttpEndPoint { get; private set; }\n\n        public readonly ClusterVNode Node;\n        public readonly TFChunkDb Db;\n        private readonly string _dbPath;\n        public ManualResetEvent StartedEvent;\n\n        public MiniClusterNode(\n            string pathname, int debugIndex, IPEndPoint internalTcp, IPEndPoint internalTcpSec, IPEndPoint internalHttp,\n            IPEndPoint externalTcp, IPEndPoint externalTcpSec, IPEndPoint externalHttp, IPEndPoint[] gossipSeeds,\n            ISubsystem[] subsystems = null, int? chunkSize = null, int? cachedChunkSize = null,\n            bool enableTrustedAuth = false, bool skipInitializeStandardUsersCheck = true, int memTableSize = 1000,\n            bool inMemDb = true, bool disableFlushToDisk = false)\n        {\n            RunningTime.Start();\n            RunCount += 1;\n            _\n            _dbPath = Path.Combine(\n                pathname,\n                string.Format(\n                    \"mini-cluster-node-db-{0}-{1}-{2}\", externalTcp.Port, externalTcpSec.Port, externalHttp.Port));\n\n            Directory.CreateDirectory(_dbPath);\n            FileStreamExtensions.ConfigureFlush(disableFlushToDisk);\n            Db =\n                new TFChunkDb(\n                    CreateDbConfig(chunkSize ?? ChunkSize, _dbPath, cachedChunkSize ?? CachedChunkSize, inMemDb));\n\n            InternalTcpEndPoint = internalTcp;\n            InternalTcpSecEndPoint = internalTcpSec;\n            InternalHttpEndPoint = internalHttp;\n\n            ExternalTcpEndPoint = externalTcp;\n            ExternalTcpSecEndPoint = externalTcpSec;\n            ExternalHttpEndPoint = externalHttp;\n\n            var singleVNodeSettings = new ClusterVNodeSettings(\n                Guid.NewGuid(), debugIndex, InternalTcpEndPoint, InternalTcpSecEndPoint, ExternalTcpEndPoint,\n                ExternalTcpSecEndPoint, InternalHttpEndPoint, ExternalHttpEndPoint,\n                new[] {ExternalHttpEndPoint.ToHttpUrl()}, enableTrustedAuth, ssl_connections.GetCertificate(), 1, false,\n                \"\", gossipSeeds, TFConsts.MinFlushDelayMs, 3, 2, 2, TimeSpan.FromSeconds(2), TimeSpan.FromSeconds(2),\n                false, \"\", false, TimeSpan.FromHours(1), StatsStorage.None, 0,\n                new InternalAuthenticationProviderFactory(), disableScavengeMerging: true, adminOnPublic: true,\n                statsOnPublic: true, gossipOnPublic: true, gossipInterval: TimeSpan.FromSeconds(1),\n                gossipAllowedTimeDifference: TimeSpan.FromSeconds(1), gossipTimeout: TimeSpan.FromSeconds(1),\n                extTcpHeartbeatTimeout: TimeSpan.FromSeconds(10), extTcpHeartbeatInterval: TimeSpan.FromSeconds(10),\n                intTcpHeartbeatTimeout: TimeSpan.FromSeconds(10), intTcpHeartbeatInterval: TimeSpan.FromSeconds(10),\n                verifyDbHash: false, maxMemtableEntryCount: memTableSize);\n\n            Log.Info(\n                \"\\n{0,-25} {1} ({2}/{3}, {4})\\n\" + \"{5,-25} {6} ({7})\\n\" + \"{8,-25} {9} ({10}-bit)\\n\"\n                + \"{11,-25} {12}\\n\" + \"{13,-25} {14}\\n\" + \"{15,-25} {16}\\n\" + \"{17,-25} {18}\\n\" + \"{19,-25} {20}\\n\\n\",\n                \"ES VERSION:\", VersionInfo.Version, VersionInfo.Branch, VersionInfo.Hashtag, VersionInfo.Timestamp,\n                \"OS:\", OS.OsFlavor, Environment.OSVersion, \"RUNTIME:\", OS.GetRuntimeVersion(),\n                Marshal.SizeOf(typeof (IntPtr))*8, \"GC:\",\n                GC.MaxGeneration == 0\n                    ? \"NON-GENERATION (PROBABLY BOEHM)\"\n                    : string.Format(\"{0} GENERATIONS\", GC.MaxGeneration + 1), \"DBPATH:\", _dbPath, \"ExTCP ENDPOINT:\",\n                ExternalTcpEndPoint, \"ExTCP SECURE ENDPOINT:\", ExternalTcpSecEndPoint, \"ExHTTP ENDPOINT:\",\n                ExternalHttpEndPoint);\n\n            Node = new ClusterVNode(Db, singleVNodeSettings, infoController: new InfoController(null, ProjectionType.None), subsystems: subsystems, gossipSeedSource: new KnownEndpointGossipSeedSource(gossipSeeds));\n            Node.ExternalHttpService.SetupController(new TestController(Node.MainQueue));\n        }\n\n        public void Start()\n        {\n            StartingTime.Start();\n\n            StartedEvent = new ManualResetEvent(false);\n            Node.MainBus.Subscribe(\n                new AdHocHandler<SystemMessage.SystemStart>(m => StartedEvent.Set()));\n\n            Node.Start();\n\n            //if (!StartedEvent.Wait(60000))\n            //    throw new TimeoutException(\"MiniNode haven't started in 60 seconds.\");\n\n            //StartingTime.Stop();\n        }\n\n        public void Shutdown(bool keepDb = false, bool keepPorts = false)\n        {\n            StoppingTime.Start();\n\n            var shutdownEvent = new ManualResetEventSlim(false);\n            Node.MainBus.Subscribe(new AdHocHandler<SystemMessage.BecomeShutdown>(m => shutdownEvent.Set()));\n\n            Node.Stop();\n\n            if (!shutdownEvent.Wait(20000))\n                throw new TimeoutException(\"MiniNode haven't shut down in 20 seconds.\");\n\n            if (!keepPorts)\n            {\n                PortsHelper.ReturnPort(InternalTcpEndPoint.Port);\n                PortsHelper.ReturnPort(InternalTcpSecEndPoint.Port);\n                PortsHelper.ReturnPort(InternalHttpEndPoint.Port);\n                PortsHelper.ReturnPort(ExternalTcpEndPoint.Port);\n                PortsHelper.ReturnPort(ExternalTcpSecEndPoint.Port);\n                PortsHelper.ReturnPort(ExternalHttpEndPoint.Port);\n            }\n\n            if (!keepDb)\n                TryDeleteDirectory(_dbPath);\n\n            StoppingTime.Stop();\n            RunningTime.Stop();\n        }\n\n        private void TryDeleteDirectory(string directory)\n        {\n            try\n            {\n                Directory.Delete(directory, true);\n            }\n            catch (Exception e)\n            {\n                Debug.WriteLine(\"Failed to remove directory {0}\", directory);\n                Debug.WriteLine(e);\n            }\n        }\n\n        private TFChunkDbConfig CreateDbConfig(int chunkSize, string dbPath, long chunksCacheSize, bool inMemDb)\n        {\n            ICheckpoint writerChk;\n            ICheckpoint chaserChk;\n            ICheckpoint epochChk;\n            ICheckpoint truncateChk;\n            if (inMemDb)\n            {\n                writerChk = new InMemoryCheckpoint(Checkpoint.Writer);\n                chaserChk = new InMemoryCheckpoint(Checkpoint.Chaser);\n                epochChk = new InMemoryCheckpoint(Checkpoint.Epoch, initValue: -1);\n                truncateChk = new InMemoryCheckpoint(Checkpoint.Truncate, initValue: -1);\n            }\n            else\n            {\n                var writerCheckFilename = Path.Combine(dbPath, Checkpoint.Writer + \".chk\");\n                var chaserCheckFilename = Path.Combine(dbPath, Checkpoint.Chaser + \".chk\");\n                var epochCheckFilename = Path.Combine(dbPath, Checkpoint.Epoch + \".chk\");\n                var truncateCheckFilename = Path.Combine(dbPath, Checkpoint.Truncate + \".chk\");\n                if (Runtime.IsMono)\n                {\n                    writerChk = new FileCheckpoint(writerCheckFilename, Checkpoint.Writer, cached: true);\n                    chaserChk = new FileCheckpoint(chaserCheckFilename, Checkpoint.Chaser, cached: true);\n                    epochChk = new FileCheckpoint(epochCheckFilename, Checkpoint.Epoch, cached: true, initValue: -1);\n                    truncateChk = new FileCheckpoint(\n                        truncateCheckFilename, Checkpoint.Truncate, cached: true, initValue: -1);\n                }\n                else\n                {\n                    writerChk = new MemoryMappedFileCheckpoint(writerCheckFilename, Checkpoint.Writer, cached: true);\n                    chaserChk = new MemoryMappedFileCheckpoint(chaserCheckFilename, Checkpoint.Chaser, cached: true);\n                    epochChk = new MemoryMappedFileCheckpoint(\n                        epochCheckFilename, Checkpoint.Epoch, cached: true, initValue: -1);\n                    truncateChk = new MemoryMappedFileCheckpoint(\n                        truncateCheckFilename, Checkpoint.Truncate, cached: true, initValue: -1);\n                }\n            }\n            var nodeConfig = new TFChunkDbConfig(\n                dbPath, new VersionedPatternFileNamingStrategy(dbPath, \"chunk-\"), chunkSize, chunksCacheSize, writerChk,\n                chaserChk, epochChk, truncateChk, inMemDb);\n            return nodeConfig;\n        }\n    }\n}\n", "line": "60"}
Traceback (most recent call last):
  File "X/urllib/request.py", line 1252, in do_open
  File "X/http/client.py", line 1049, in request
  File "X/http/client.py", line 1087, in _send_request
  File "X/http/client.py", line 1045, in endheaders
  File "X/http/client.py", line 890, in _send_output
  File "X/http/client.py", line 828, in send
  File "X/http/client.py", line 806, in connect
  File "X/socket.py", line 424, in create_connection
  File "X/socket.py", line 415, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/greg/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 40, in run
    response = opener.open(url, data, timeout)
  File "X/urllib/request.py", line 473, in open
  File "X/urllib/request.py", line 491, in _open
  File "X/urllib/request.py", line 451, in _call_chain
  File "X/urllib/request.py", line 1272, in http_open
  File "X/urllib/request.py", line 1255, in do_open
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
======== response ========
None
CALLBACK_ERROR
project file is : /Users/greg/Code/EventStore/src/EventStore.sublime-project
response: /Users/greg/Code/EventStore/src/EventStore.sln
request: http://localhost:50476/autocomplete
======== request params ======== 
 {"wordToComplete": "", "WantReturnType": true, "column": "21", "WantSnippet": true, "filename": "/Users/greg/Code/EventStore/src/EventStore.Core.Tests/Helpers/MiniClusterNode.cs", "WantMethodHeader": true, "buffer": "using System;\nusing System.Diagnostics;\nusing System.IO;\nusing System.Linq;\nusing System.Net;\nusing System.Net.Sockets;\nusing System.Runtime.InteropServices;\nusing System.Threading;\nusing EventStore.Common.Log;\nusing EventStore.Common.Options;\nusing EventStore.Common.Utils;\nusing EventStore.Core.Authentication;\nusing EventStore.Core.Bus;\nusing EventStore.Core.Cluster.Settings;\nusing EventStore.Core.Messages;\nusing EventStore.Core.Services.Gossip;\nusing EventStore.Core.Services.Monitoring;\nusing EventStore.Core.Tests.Http;\nusing EventStore.Core.Tests.Services.Transport.Tcp;\nusing EventStore.Core.TransactionLog.Checkpoint;\nusing EventStore.Core.TransactionLog.Chunks;\nusing EventStore.Core.TransactionLog.FileNamingStrategy;\nusing EventStore.Core.Services.Transport.Http.Controllers;\n\nnamespace EventStore.Core.Tests.Helpers\n{\n    public class MiniClusterNode\n    {\n        public static int RunCount = 0;\n        public static readonly Stopwatch RunningTime = new Stopwatch();\n        public static readonly Stopwatch StartingTime = new Stopwatch();\n        public static readonly Stopwatch StoppingTime = new Stopwatch();\n\n        public const int ChunkSize = 1024*1024;\n        public const int CachedChunkSize = ChunkSize + ChunkHeader.Size + ChunkFooter.Size;\n\n        private static readonly ILogger Log = LogManager.GetLoggerFor<MiniClusterNode>();\n\n        public IPEndPoint InternalTcpEndPoint { get; private set; }\n        public IPEndPoint InternalTcpSecEndPoint { get; private set; }\n        public IPEndPoint InternalHttpEndPoint { get; private set; }\n        public IPEndPoint ExternalTcpEndPoint { get; private set; }\n        public IPEndPoint ExternalTcpSecEndPoint { get; private set; }\n        public IPEndPoint ExternalHttpEndPoint { get; private set; }\n\n        public readonly ClusterVNode Node;\n        public readonly TFChunkDb Db;\n        private readonly string _dbPath;\n        public ManualResetEvent StartedEvent;\n\n        public MiniClusterNode(\n            string pathname, int debugIndex, IPEndPoint internalTcp, IPEndPoint internalTcpSec, IPEndPoint internalHttp,\n            IPEndPoint externalTcp, IPEndPoint externalTcpSec, IPEndPoint externalHttp, IPEndPoint[] gossipSeeds,\n            ISubsystem[] subsystems = null, int? chunkSize = null, int? cachedChunkSize = null,\n            bool enableTrustedAuth = false, bool skipInitializeStandardUsersCheck = true, int memTableSize = 1000,\n            bool inMemDb = true, bool disableFlushToDisk = false)\n        {\n            RunningTime.Start();\n            RunCount += 1;\n            _dbPath.\n            _dbPath = Path.Combine(\n                pathname,\n                string.Format(\n                    \"mini-cluster-node-db-{0}-{1}-{2}\", externalTcp.Port, externalTcpSec.Port, externalHttp.Port));\n\n            Directory.CreateDirectory(_dbPath);\n            FileStreamExtensions.ConfigureFlush(disableFlushToDisk);\n            Db =\n                new TFChunkDb(\n                    CreateDbConfig(chunkSize ?? ChunkSize, _dbPath, cachedChunkSize ?? CachedChunkSize, inMemDb));\n\n            InternalTcpEndPoint = internalTcp;\n            InternalTcpSecEndPoint = internalTcpSec;\n            InternalHttpEndPoint = internalHttp;\n\n            ExternalTcpEndPoint = externalTcp;\n            ExternalTcpSecEndPoint = externalTcpSec;\n            ExternalHttpEndPoint = externalHttp;\n\n            var singleVNodeSettings = new ClusterVNodeSettings(\n                Guid.NewGuid(), debugIndex, InternalTcpEndPoint, InternalTcpSecEndPoint, ExternalTcpEndPoint,\n                ExternalTcpSecEndPoint, InternalHttpEndPoint, ExternalHttpEndPoint,\n                new[] {ExternalHttpEndPoint.ToHttpUrl()}, enableTrustedAuth, ssl_connections.GetCertificate(), 1, false,\n                \"\", gossipSeeds, TFConsts.MinFlushDelayMs, 3, 2, 2, TimeSpan.FromSeconds(2), TimeSpan.FromSeconds(2),\n                false, \"\", false, TimeSpan.FromHours(1), StatsStorage.None, 0,\n                new InternalAuthenticationProviderFactory(), disableScavengeMerging: true, adminOnPublic: true,\n                statsOnPublic: true, gossipOnPublic: true, gossipInterval: TimeSpan.FromSeconds(1),\n                gossipAllowedTimeDifference: TimeSpan.FromSeconds(1), gossipTimeout: TimeSpan.FromSeconds(1),\n                extTcpHeartbeatTimeout: TimeSpan.FromSeconds(10), extTcpHeartbeatInterval: TimeSpan.FromSeconds(10),\n                intTcpHeartbeatTimeout: TimeSpan.FromSeconds(10), intTcpHeartbeatInterval: TimeSpan.FromSeconds(10),\n                verifyDbHash: false, maxMemtableEntryCount: memTableSize);\n\n            Log.Info(\n                \"\\n{0,-25} {1} ({2}/{3}, {4})\\n\" + \"{5,-25} {6} ({7})\\n\" + \"{8,-25} {9} ({10}-bit)\\n\"\n                + \"{11,-25} {12}\\n\" + \"{13,-25} {14}\\n\" + \"{15,-25} {16}\\n\" + \"{17,-25} {18}\\n\" + \"{19,-25} {20}\\n\\n\",\n                \"ES VERSION:\", VersionInfo.Version, VersionInfo.Branch, VersionInfo.Hashtag, VersionInfo.Timestamp,\n                \"OS:\", OS.OsFlavor, Environment.OSVersion, \"RUNTIME:\", OS.GetRuntimeVersion(),\n                Marshal.SizeOf(typeof (IntPtr))*8, \"GC:\",\n                GC.MaxGeneration == 0\n                    ? \"NON-GENERATION (PROBABLY BOEHM)\"\n                    : string.Format(\"{0} GENERATIONS\", GC.MaxGeneration + 1), \"DBPATH:\", _dbPath, \"ExTCP ENDPOINT:\",\n                ExternalTcpEndPoint, \"ExTCP SECURE ENDPOINT:\", ExternalTcpSecEndPoint, \"ExHTTP ENDPOINT:\",\n                ExternalHttpEndPoint);\n\n            Node = new ClusterVNode(Db, singleVNodeSettings, infoController: new InfoController(null, ProjectionType.None), subsystems: subsystems, gossipSeedSource: new KnownEndpointGossipSeedSource(gossipSeeds));\n            Node.ExternalHttpService.SetupController(new TestController(Node.MainQueue));\n        }\n\n        public void Start()\n        {\n            StartingTime.Start();\n\n            StartedEvent = new ManualResetEvent(false);\n            Node.MainBus.Subscribe(\n                new AdHocHandler<SystemMessage.SystemStart>(m => StartedEvent.Set()));\n\n            Node.Start();\n\n            //if (!StartedEvent.Wait(60000))\n            //    throw new TimeoutException(\"MiniNode haven't started in 60 seconds.\");\n\n            //StartingTime.Stop();\n        }\n\n        public void Shutdown(bool keepDb = false, bool keepPorts = false)\n        {\n            StoppingTime.Start();\n\n            var shutdownEvent = new ManualResetEventSlim(false);\n            Node.MainBus.Subscribe(new AdHocHandler<SystemMessage.BecomeShutdown>(m => shutdownEvent.Set()));\n\n            Node.Stop();\n\n            if (!shutdownEvent.Wait(20000))\n                throw new TimeoutException(\"MiniNode haven't shut down in 20 seconds.\");\n\n            if (!keepPorts)\n            {\n                PortsHelper.ReturnPort(InternalTcpEndPoint.Port);\n                PortsHelper.ReturnPort(InternalTcpSecEndPoint.Port);\n                PortsHelper.ReturnPort(InternalHttpEndPoint.Port);\n                PortsHelper.ReturnPort(ExternalTcpEndPoint.Port);\n                PortsHelper.ReturnPort(ExternalTcpSecEndPoint.Port);\n                PortsHelper.ReturnPort(ExternalHttpEndPoint.Port);\n            }\n\n            if (!keepDb)\n                TryDeleteDirectory(_dbPath);\n\n            StoppingTime.Stop();\n            RunningTime.Stop();\n        }\n\n        private void TryDeleteDirectory(string directory)\n        {\n            try\n            {\n                Directory.Delete(directory, true);\n            }\n            catch (Exception e)\n            {\n                Debug.WriteLine(\"Failed to remove directory {0}\", directory);\n                Debug.WriteLine(e);\n            }\n        }\n\n        private TFChunkDbConfig CreateDbConfig(int chunkSize, string dbPath, long chunksCacheSize, bool inMemDb)\n        {\n            ICheckpoint writerChk;\n            ICheckpoint chaserChk;\n            ICheckpoint epochChk;\n            ICheckpoint truncateChk;\n            if (inMemDb)\n            {\n                writerChk = new InMemoryCheckpoint(Checkpoint.Writer);\n                chaserChk = new InMemoryCheckpoint(Checkpoint.Chaser);\n                epochChk = new InMemoryCheckpoint(Checkpoint.Epoch, initValue: -1);\n                truncateChk = new InMemoryCheckpoint(Checkpoint.Truncate, initValue: -1);\n            }\n            else\n            {\n                var writerCheckFilename = Path.Combine(dbPath, Checkpoint.Writer + \".chk\");\n                var chaserCheckFilename = Path.Combine(dbPath, Checkpoint.Chaser + \".chk\");\n                var epochCheckFilename = Path.Combine(dbPath, Checkpoint.Epoch + \".chk\");\n                var truncateCheckFilename = Path.Combine(dbPath, Checkpoint.Truncate + \".chk\");\n                if (Runtime.IsMono)\n                {\n                    writerChk = new FileCheckpoint(writerCheckFilename, Checkpoint.Writer, cached: true);\n                    chaserChk = new FileCheckpoint(chaserCheckFilename, Checkpoint.Chaser, cached: true);\n                    epochChk = new FileCheckpoint(epochCheckFilename, Checkpoint.Epoch, cached: true, initValue: -1);\n                    truncateChk = new FileCheckpoint(\n                        truncateCheckFilename, Checkpoint.Truncate, cached: true, initValue: -1);\n                }\n                else\n                {\n                    writerChk = new MemoryMappedFileCheckpoint(writerCheckFilename, Checkpoint.Writer, cached: true);\n                    chaserChk = new MemoryMappedFileCheckpoint(chaserCheckFilename, Checkpoint.Chaser, cached: true);\n                    epochChk = new MemoryMappedFileCheckpoint(\n                        epochCheckFilename, Checkpoint.Epoch, cached: true, initValue: -1);\n                    truncateChk = new MemoryMappedFileCheckpoint(\n                        truncateCheckFilename, Checkpoint.Truncate, cached: true, initValue: -1);\n                }\n            }\n            var nodeConfig = new TFChunkDbConfig(\n                dbPath, new VersionedPatternFileNamingStrategy(dbPath, \"chunk-\"), chunkSize, chunksCacheSize, writerChk,\n                chaserChk, epochChk, truncateChk, inMemDb);\n            return nodeConfig;\n        }\n    }\n}\n", "line": "60"}
Traceback (most recent call last):
  File "X/urllib/request.py", line 1252, in do_open

**Comment by threeup** [comment]
I had this issue and resolved it by removing two lines from the omni sharp launcher
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = subprocess.SW_HIDE

**Comment by Figbash** [comment]
I'm having the same issue, also in OS X.  However it works with what I believe is the exact same setup on my other computer (newest mono, mavericks, package is in dropbox).  If I manually run OmniSharpServer using the port Sublime says it's launching it with then everything works...  I tried removing the above lines but no luck.  Anyone figure it out yet?

**Comment by Figbash** [comment]
After messing with it some more, mine will work if I comment out -c config like so:
def start_omni_sharp_server(mono_exe_path, omni_exe_path, solution_path, port, config_file):
    if os.name == 'posix':
        args = [
            mono_exe_path, 
            omni_exe_path, 
            '-s', solution_path,
            '-p', str(port)
            # ,
            # '-config', config_file
        ]

I don't know how it would have a bad config.json, as I have never modified it and it works fine on the other computer with the same one through dropbox, but it's a clue :)

**Comment by jchannon** [comment]
Can you re-test with v1.8.1 of the plugin and if still an issue let me know
